apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  shareProcessNamespace: true
  containers:
    - image: nginx
      name: nginx
    - name: shell
      image: busybox
      stdin: true
      tty: true
